// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sittax.Cnpj.Data;

#nullable disable

namespace Sittax.Cnpj.Migrations
{
    [DbContext(typeof(SittaxCnpjDbContext))]
    [Migration("20250928150115_CreateReceitaFederalLogArquivosTable")]
    partial class CreateReceitaFederalLogArquivosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sittax.Cnpj.Models.ReceitaFederalLogArquivos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataDownload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_download");

                    b.Property<string>("HashSha256Csv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256_csv");

                    b.Property<string>("HashSha256Zip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256_zip");

                    b.Property<string>("NomeArquivoCsv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo_csv");

                    b.Property<string>("NomeArquivoZip")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo_zip");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.Property<int>("StatusCsv")
                        .HasColumnType("integer")
                        .HasColumnName("status_csv");

                    b.Property<int>("StatusDownload")
                        .HasColumnType("integer")
                        .HasColumnName("status_download");

                    b.Property<long?>("TamanhoCsv")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_csv");

                    b.Property<long>("TamanhoZip")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_zip");

                    b.Property<DateTime>("UltimaVerificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_verificacao");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NomeArquivoZip");

                    b.HasIndex("Periodo");

                    b.HasIndex("NomeArquivoZip", "Periodo")
                        .IsUnique();

                    b.ToTable("rf_log_arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
